
#' Example survival dataset (Weibull, admin follow-up to 10)
#'
#' @description
#' Simulated cohort; administratively truncated at 10; ~40% censoring.
#' Generated by `demo_sim_weibull(shape = 1.6, S20 = 0.20, t_max = 10, n = 1500, seed = 1)`.
#'
#' Example survival dataset (Weibull, admin follow-up to 10)
#' @format A data frame with 1,500 rows and 3 columns: id, time, status.
#' @usage data(survblendr_demo)
#' @keywords datasets
"survblendr_demo"
